# Generated by Django 4.0.5 on 2022-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.ImageField(blank=True, upload_to='QRcode'),
        ),
    ]
